<!DOCTYPE HTML>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="keywords" content="05. Selection, Python, Pandas">
    <meta name="description" content="Just to take notes for what I have learnt, and I will be very happy if it helps anyone.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="renderer" content="webkit|ie-stand|ie-comp">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <!-- Global site tag (gtag.js) - Google Analytics -->


    <title>05. Selection | Ford Yang&#39;s Blog</title>
    <link rel="icon" type="image/png" href="/favicon.png">

    <link rel="stylesheet" type="text/css" href="/libs/awesome/css/all.css">
    <link rel="stylesheet" type="text/css" href="/libs/materialize/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/aos/aos.css">
    <link rel="stylesheet" type="text/css" href="/libs/animate/animate.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/lightGallery/css/lightgallery.min.css">
    <link rel="stylesheet" type="text/css" href="/css/matery.css">
    <link rel="stylesheet" type="text/css" href="/css/my.css">

    <script src="/libs/jquery/jquery.min.js"></script>

<meta name="generator" content="Hexo 4.2.0"><link rel="alternate" href="/atom.xml" title="Ford Yang's Blog" type="application/atom+xml">
<link rel="stylesheet" href="/css/prism-tomorrow.css" type="text/css"></head>


<body>
    <header class="navbar-fixed">
    <nav id="headNav" class="bg-color nav-transparent">
        <div id="navContainer" class="nav-wrapper container">
            <div class="brand-logo">
                <a href="/" class="waves-effect waves-light">
                    
                    <img src="/medias/logo.png" class="logo-img" alt="LOGO">
                    
                    <span class="logo-span">Ford Yang&#39;s Blog</span>
                </a>
            </div>
            

<a href="#" data-target="mobile-nav" class="sidenav-trigger button-collapse"><i class="fas fa-bars"></i></a>
<ul class="right nav-menu">
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/" class="waves-effect waves-light">
      
      <i class="fas fa-home" style="zoom: 0.6;"></i>
      
      <span>Index</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/tags" class="waves-effect waves-light">
      
      <i class="fas fa-tags" style="zoom: 0.6;"></i>
      
      <span>Tags</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/categories" class="waves-effect waves-light">
      
      <i class="fas fa-bookmark" style="zoom: 0.6;"></i>
      
      <span>Categories</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/archives" class="waves-effect waves-light">
      
      <i class="fas fa-archive" style="zoom: 0.6;"></i>
      
      <span>Archives</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/about" class="waves-effect waves-light">
      
      <i class="fas fa-user-circle" style="zoom: 0.6;"></i>
      
      <span>About</span>
    </a>
    
  </li>
  
  <li>
    <a href="#searchModal" class="modal-trigger waves-effect waves-light">
      <i id="searchIcon" class="fas fa-search" title="Search" style="zoom: 0.85;"></i>
    </a>
  </li>
</ul>


<div id="mobile-nav" class="side-nav sidenav">

    <div class="mobile-head bg-color">
        
        <img src="/medias/logo.png" class="logo-img circle responsive-img">
        
        <div class="logo-name">Ford Yang&#39;s Blog</div>
        <div class="logo-desc">
            
            Just to take notes for what I have learnt, and I will be very happy if it helps anyone.
            
        </div>
    </div>

    

    <ul class="menu-list mobile-menu-list">
        
        <li class="m-nav-item">
	  
		<a href="/" class="waves-effect waves-light">
			
			    <i class="fa-fw fas fa-home"></i>
			
			Index
		</a>
          
        </li>
        
        <li class="m-nav-item">
	  
		<a href="/tags" class="waves-effect waves-light">
			
			    <i class="fa-fw fas fa-tags"></i>
			
			Tags
		</a>
          
        </li>
        
        <li class="m-nav-item">
	  
		<a href="/categories" class="waves-effect waves-light">
			
			    <i class="fa-fw fas fa-bookmark"></i>
			
			Categories
		</a>
          
        </li>
        
        <li class="m-nav-item">
	  
		<a href="/archives" class="waves-effect waves-light">
			
			    <i class="fa-fw fas fa-archive"></i>
			
			Archives
		</a>
          
        </li>
        
        <li class="m-nav-item">
	  
		<a href="/about" class="waves-effect waves-light">
			
			    <i class="fa-fw fas fa-user-circle"></i>
			
			About
		</a>
          
        </li>
        
        
    </ul>
</div>


        </div>

        
    </nav>

</header>

    
<script src="/libs/cryptojs/crypto-js.min.js"></script>
<script>
    (function() {
        let pwd = '';
        if (pwd && pwd.length > 0) {
            if (pwd !== CryptoJS.SHA256(prompt('please input the password')).toString(CryptoJS.enc.Hex)) {
                alert('Wrong password, return to the main page.');
                location.href = '/';
            }
        }
    })();
</script>




<div class="bg-cover pd-header post-cover" style="background-image: url('/medias/featureimages/19.jpg')">
    <div class="container" style="right: 0px;left: 0px;">
        <div class="row">
            <div class="col s12 m12 l12">
                <div class="brand">
                    <h1 class="description center-align post-title">05. Selection</h1>
                </div>
            </div>
        </div>
    </div>
</div>




<main class="post-container content">

    
    <link rel="stylesheet" href="/libs/tocbot/tocbot.css">
<style>
    #articleContent h1::before,
    #articleContent h2::before,
    #articleContent h3::before,
    #articleContent h4::before,
    #articleContent h5::before,
    #articleContent h6::before {
        display: block;
        content: " ";
        height: 100px;
        margin-top: -100px;
        visibility: hidden;
    }

    #articleContent :focus {
        outline: none;
    }

    .toc-fixed {
        position: fixed;
        top: 64px;
    }

    .toc-widget {
        width: 345px;
        padding-left: 20px;
    }

    .toc-widget .toc-title {
        margin: 35px 0 15px 0;
        padding-left: 17px;
        font-size: 1.5rem;
        font-weight: bold;
        line-height: 1.5rem;
    }

    .toc-widget ol {
        padding: 0;
        list-style: none;
    }

    #toc-content {
        height: calc(100vh - 250px);
        overflow: auto;
    }

    #toc-content ol {
        padding-left: 10px;
    }

    #toc-content ol li {
        padding-left: 10px;
    }

    #toc-content .toc-link:hover {
        color: #42b983;
        font-weight: 700;
        text-decoration: underline;
    }

    #toc-content .toc-link::before {
        background-color: transparent;
        max-height: 25px;

        position: absolute;
        right: 23.5vw;
        display: block;
    }

    #toc-content .is-active-link {
        color: #42b983;
    }

    #floating-toc-btn {
        position: fixed;
        right: 15px;
        bottom: 76px;
        padding-top: 15px;
        margin-bottom: 0;
        z-index: 998;
    }

    #floating-toc-btn .btn-floating {
        width: 48px;
        height: 48px;
    }

    #floating-toc-btn .btn-floating i {
        line-height: 48px;
        font-size: 1.4rem;
    }
</style>
<div class="row">
    <div id="main-content" class="col s12 m12 l9">
        <!-- 文章内容详情 -->
<div id="artDetail">
    <div class="card">
        <div class="card-content article-info">
            <div class="row tag-cate">
                <div class="col s7">
                    
                    <div class="article-tag">
                        
                            <a href="/tags/AutoCAD-API/">
                                <span class="chip bg-color">AutoCAD API</span>
                            </a>
                        
                            <a href="/tags/C/">
                                <span class="chip bg-color">C#</span>
                            </a>
                        
                    </div>
                    
                </div>
                <div class="col s5 right-align">
                    
                    <div class="post-cate">
                        <i class="fas fa-bookmark fa-fw icon-category"></i>
                        
                            <a href="/categories/August-2020/" class="post-category">
                                August 2020
                            </a>
                        
                    </div>
                    
                </div>
            </div>

            <div class="post-info">
                
                <div class="post-date info-break-policy">
                    <i class="far fa-calendar-minus fa-fw"></i>Publish Date:&nbsp;&nbsp;
                    2020-08-30
                </div>
                

                

                
                <div class="info-break-policy">
                    <i class="far fa-file-word fa-fw"></i>Word Count:&nbsp;&nbsp;
                    1.1k
                </div>
                

                
                <div class="info-break-policy">
                    <i class="far fa-clock fa-fw"></i>Read Times:&nbsp;&nbsp;
                    6 Min
                </div>
                

                
            </div>
        </div>
        <hr class="clearfix">
        <div class="card-content article-card-content">
            <div id="articleContent">
                <h2 id="Introduction">Introduction</h2>
<p>Today we will learn how to interact with AutoCAD.</p>
<h2 id="Select-Objects-in-the-Drawing-Area">Select Objects in the Drawing Area</h2>
<p>You can select objects through by having the user interactively select objects, or you can simulate many of the various object selection options through the .NET API. If your routine performs multiple selection sets, you will need to either track each selection set returned or create an ObjectIdCollection object to keep track of all the selected objects. The following functions allow you to select objects from the drawing:</p>
<ul>
<li>
<p>GetSelection</p>
<p>Prompts the user to pick objects from the screen.</p>
</li>
<li>
<p>SelectAll</p>
<p>Selects all objects in the current space in which are not locked or frozen.</p>
</li>
<li>
<p>SelectCrossingPolygon</p>
<p>Selects objects within and crossing a polygon defined by specifying points. The polygon can be any shape but cannot cross or touch itself.</p>
</li>
<li>
<p>SelectCrossingWindow</p>
<p>Selects objects within and crossing an area defined by two points.</p>
</li>
<li>
<p>SelectFence</p>
<p>Selects all objects crossing a selection fence. Fence selection is similar to crossing polygon selection except that the fence is not closed, and a fence can cross itself.</p>
</li>
<li>
<p>SelectLast</p>
<p>Selects the last object created in the current space.</p>
</li>
<li>
<p>SelectPrevious</p>
<p>Selects all objects selected during the previous Select objects: prompt.</p>
</li>
<li>
<p>SelectWindow</p>
<p>Selects all objects completely inside a rectangle defined by two points.</p>
</li>
<li>
<p>SelectWindowPolygon</p>
<p>Selects objects completely inside a polygon defined by points. The polygon can be any shape but cannot cross or touch itself.</p>
</li>
<li>
<p>SelectAtPoint</p>
<p>Selects objects passing through a given point and places them into the active selection set.</p>
</li>
<li>
<p>SelectByPolygon</p>
<p>Selects objects within a fence and adds them to the active selection set.</p>
</li>
</ul>
<h2 id="Add-selected-objects-to-a-selection-set">Add selected objects to a selection set</h2>
<p>This example prompts the user to select objects twice and then merges the two selection sets created into a single selection set.</p>
<pre class=" language-language-C#"><code class="language-language-C#">using Autodesk.AutoCAD.Runtime;
using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
 
[CommandMethod("MergeSelectionSets")]
public static void MergeSelectionSets()
{
  // Get the current document editor
  Editor acDocEd = Application.DocumentManager.MdiActiveDocument.Editor;
 
  // Request for objects to be selected in the drawing area
  PromptSelectionResult acSSPrompt;
  acSSPrompt = acDocEd.GetSelection();
 
  SelectionSet acSSet1;
  ObjectIdCollection acObjIdColl = new ObjectIdCollection();
 
  // If the prompt status is OK, objects were selected
  if (acSSPrompt.Status == PromptStatus.OK)
  {
      // Get the selected objects
      acSSet1 = acSSPrompt.Value;
 
      // Append the selected objects to the ObjectIdCollection
      acObjIdColl = new ObjectIdCollection(acSSet1.GetObjectIds());
  }
 
  // Request for objects to be selected in the drawing area
  acSSPrompt = acDocEd.GetSelection();
 
  SelectionSet acSSet2;
 
  // If the prompt status is OK, objects were selected
  if (acSSPrompt.Status == PromptStatus.OK)
  {
      acSSet2 = acSSPrompt.Value;
 
      // Check the size of the ObjectIdCollection, if zero, then initialize it
      if (acObjIdColl.Count == 0)
      {
          acObjIdColl = new ObjectIdCollection(acSSet2.GetObjectIds());
      }
      else
      {
          // Step through the second selection set
          foreach (ObjectId acObjId in acSSet2.GetObjectIds())
          {
              // Add each object id to the ObjectIdCollection
              acObjIdColl.Add(acObjId);
          }
      }
  }
 
  Application.ShowAlertDialog("Number of objects selected: " +
                              acObjIdColl.Count.ToString());
}
</code></pre>
<h2 id="Define-Rules-for-selection-Filters">Define Rules for selection Filters</h2>
<table>
<thead>
<tr>
<th>DXF CODES</th>
<th>Filter Type</th>
</tr>
</thead>
<tbody>
<tr>
<td>0 (or DxfCode.Start)</td>
<td>Object Type (String)Such as “Line,” “Circle,” “Arc,” and so forth.</td>
</tr>
<tr>
<td>2 (or DxfCode.BlockName)</td>
<td>Block Name (String)The block name of an insert reference.</td>
</tr>
<tr>
<td>8 or (DxfCode.LayerName)</td>
<td>Layer Name (String)Such as “Layer 0.”</td>
</tr>
<tr>
<td>60 (DxfCode.Visibility)</td>
<td>Object Visibility (Integer)Use 0 = visible, 1 = invisible.</td>
</tr>
<tr>
<td>62 (or DxfCode.Color)</td>
<td>Color Number (Integer)Numeric index values ranging from 0 to 256.Zero indicates BYBLOCK. 256 indicates BYLAYER. A negative value indicates that the layer is turned off.</td>
</tr>
<tr>
<td>67</td>
<td>Model/paper space indicator (Integer)Use 0 or omitted = model space, 1 = paper space.</td>
</tr>
</tbody>
</table>
<p><strong>Relational operators for selection set filter lists</strong></p>
<table>
<thead>
<tr>
<th>Operator</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>“”"*"""</td>
<td>Anything goes (always true)</td>
</tr>
<tr>
<td>“”"="""</td>
<td>Equals</td>
</tr>
<tr>
<td>“”"!="""</td>
<td>Not equal to</td>
</tr>
<tr>
<td>“”"/="""</td>
<td>Not equal to</td>
</tr>
<tr>
<td>“”"&lt;&gt;"""</td>
<td>Not equal to</td>
</tr>
<tr>
<td>“”"&lt;"""</td>
<td>Less than</td>
</tr>
<tr>
<td>“”"&lt;="""</td>
<td>Less than or equal to</td>
</tr>
<tr>
<td>“”"&gt;"""</td>
<td>Greater than</td>
</tr>
<tr>
<td>“”"&gt;="""</td>
<td>Greater than or equal to</td>
</tr>
<tr>
<td>“”"&amp;"""</td>
<td>Bitwise AND (integer groups only)</td>
</tr>
<tr>
<td>“”"&amp;="""</td>
<td>Bitwise masked equals (integer groups only)</td>
</tr>
</tbody>
</table>
<h3 id="Example">Example</h3>
<p>Demand: Get all the text in red color on “layer01” and all the text in blue on “lay02” and “lay03”</p>
<pre><code>&lt; or
    &lt; and
             Layer == "lay01"
             Color == "1"    // The index of Color red is 1
             Entity type == "TEXT"
    and &gt;
    &lt; and
             &lt; or
             Layer == "lay02"
             Layer == "lay03"
             or &gt;
             Color == "5"     // The index of Color Blue is 5
             Entity type == "POLYLINE"
    and &gt;
or &gt;
</code></pre>
<h3 id="Code">Code</h3>
<pre class=" language-language-C#"><code class="language-language-C#">public static void MultipleSelectionFilter()
{
    // Get the current editor
    Editor ed = Autodesk.AutoCAD.ApplicationServices.Core.Application.DocumentManager.MdiActiveDocument.Editor;

    // Create a set filter 

    // Define the filter condition
    TypedValue[] typeValue = {
     new TypedValue((int) DxfCode.Operator, "<or"),
     // Selection filter 1
     new TypedValue((int) DxfCode.Operator, "<and"),
     new TypedValue((int) DxfCode.Start, "TEXT"),
     new TypedValue((int) DxfCode.LayerName, "lay01"),
     new TypedValue((int) DxfCode.Color, "1"),
     new TypedValue((int) DxfCode.Operator, "and>"),
     // Selection filter 2
     new TypedValue((int) DxfCode.Operator, "<and"),
     new TypedValue((int) DxfCode.Start, "LWPOLYLINE"),
     new TypedValue((int) DxfCode.Color, "5"),
     new TypedValue((int) DxfCode.Operator, "<or"),
     new TypedValue((int) DxfCode.LayerName, "lay02"),
     new TypedValue((int) DxfCode.LayerName, "lay03"),
     new TypedValue((int) DxfCode.Operator, "or>"),
     new TypedValue((int) DxfCode.Operator, "and>"),
     new TypedValue((int) DxfCode.Operator, "or>")
    };
    
    // put the condition into the filter 
    SelectionFilter selFiter = new SelectionFilter(typeValue);

    // get the filtered result
    PromptSelectionResult psr = ed.GetSelection(selFiter);


    

    //  Check the result 
    if (psr.Status == PromptStatus.OK)
    {
        SelectionSet sSet = psr.Value;
        Autodesk.AutoCAD.ApplicationServices.Core.Application.ShowAlertDialog("Number of objects selected: " + sSet.Count.ToString());
    }
    else
    {
        Autodesk.AutoCAD.ApplicationServices.Core.Application.ShowAlertDialog("Number of objects selected: 0");
    }
}
</code></pre>
<h2 id="PromptStatus">PromptStatus</h2>
<pre class=" language-language-C#"><code class="language-language-C#">namespace Autodesk.AutoCAD.EditorInput
{
    public enum PromptStatus
    {
        Keyword = -5005,
        Cancel = -5002,
        Error = -5001,
        None = 5000,
        Modeless = 5027,
        Other = 5028,
        OK = 5100
    }
}
</code></pre>
<h2 id=""></h2>
<pre class=" language-language-C#"><code class="language-language-C#">using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.Runtime;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AcDoNetTools;
using Autodesk.AutoCAD.DatabaseServices;

namespace _04_SelectionDemo
{
    public class Class1
    {
       
        [CommandMethod("PromptDemo")]
        public void PromptDemo()
{
            Database db = HostApplicationServices.WorkingDatabase;
            // Get the current editor
            Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
            //PromptPointResult ppr = ed.GetPoint("\n Please select the first point：");
            //if (ppr.Status == PromptStatus.OK)
            //{
            //    Point3d p1 = ppr.Value;
            //    ppr = ed.GetPoint("\n Please select the second point：");
            //    if (ppr.Status == PromptStatus.OK)
            //    {
            //        Point3d p2 = ppr.Value;
            //        db.AddLineToModeSpace(p1, p2);
            //    }
            //}

            Point3d p1 = new Point3d(0, 0, 0);
            Point3d p2 = new Point3d();

            PromptPointOptions ppo = new PromptPointOptions("Please select the first point：");
            ppo.AllowNone = true;
            PromptPointResult ppr = GetPoint(ppo);

            if (ppr.Status == PromptStatus.Cancel) return;

            if (ppr.Status == PromptStatus.OK) p1 = ppr.Value;
            ppo.Message = "Please select the second point";
            ppo.BasePoint = p1;
            ppo.UseBasePoint = true;
            ppr = GetPoint(ppo);
            if (ppr.Status == PromptStatus.Cancel) return;
            if (ppr.Status == PromptStatus.None) return;
            if (ppr.Status == PromptStatus.OK) p2 = ppr.Value;
            db.AddLineToModeSpace(p1, p2);  
        }
</code></pre>
<hr>
<h1>Reference</h1>
<p><a href="http://docs.autodesk.com/ACD/2010/ENU/AutoCAD%20.NET%20Developer' target=" _blank"="" rel="noopener" s%20guide="" index.html?url="WS1a9193826455f5ff2566ffd511ff6f8c7ca-3e30.htm,topicNumber=d0e26245" "="">http://docs.autodesk.com/ACD/2010/ENU/AutoCAD .NET Developer’s Guide/index.html?url=WS1a9193826455f5ff2566ffd511ff6f8c7ca-3e30.htm,topicNumber=d0e26245</a></p>
<p><a href="http://docs.autodesk.com/ACD/2011/CHS/filesDXF/WSfacf1429558a55de185c428100849a0ab7-5f35.htm" target="_blank" rel="noopener">http://docs.autodesk.com/ACD/2011/CHS/filesDXF/WSfacf1429558a55de185c428100849a0ab7-5f35.htm</a></p>
<script>
        document.querySelectorAll('.github-emoji')
          .forEach(el => {
            if (!el.dataset.src) { return; }
            const img = document.createElement('img');
            img.style = 'display:none !important;';
            img.src = el.dataset.src;
            img.addEventListener('error', () => {
              img.remove();
              el.style.color = 'inherit';
              el.style.backgroundImage = 'none';
              el.style.background = 'none';
            });
            img.addEventListener('load', () => {
              img.remove();
            });
            document.body.appendChild(img);
          });
      </script>
            </div>
            <hr/>

            

    <div class="reprint" id="reprint-statement">
        
            <div class="reprint__author">
                <span class="reprint-meta" style="font-weight: bold;">
                    <i class="fas fa-user">
                        Author:
                    </i>
                </span>
                <span class="reprint-info">
                    <a href="/about" rel="external nofollow noreferrer">Ford Yang</a>
                </span>
            </div>
            <div class="reprint__type">
                <span class="reprint-meta" style="font-weight: bold;">
                    <i class="fas fa-link">
                        Link:
                    </i>
                </span>
                <span class="reprint-info">
                    <a href="https://fordy7014.github.io/2020/08/30/20200830AutoCAD%20developer's%20tools%20--%20Selection/">https://fordy7014.github.io/2020/08/30/20200830AutoCAD%20developer's%20tools%20--%20Selection/</a>
                </span>
            </div>
            <div class="reprint__notice">
                <span class="reprint-meta" style="font-weight: bold;">
                    <i class="fas fa-copyright">
                        Reprint policy:
                    </i>
                </span>
                <span class="reprint-info">
                    All articles in this blog are used except for special statements
                    <a href="https://creativecommons.org/licenses/by/4.0/deed.zh" rel="external nofollow noreferrer" target="_blank">CC BY 4.0</a>
                    reprint polocy. If reproduced, please indicate source
                    <a href="/about" target="_blank">Ford Yang</a>
                    !
                </span>
            </div>
        
    </div>

    <script async defer>
      document.addEventListener("copy", function (e) {
        let toastHTML = '<span>Copied successfully, please follow the reprint policy of this article</span><button class="btn-flat toast-action" onclick="navToReprintStatement()" style="font-size: smaller">more</a>';
        M.toast({html: toastHTML})
      });

      function navToReprintStatement() {
        $("html, body").animate({scrollTop: $("#reprint-statement").offset().top - 80}, 800);
      }
    </script>



            <div class="tag_share" style="display: block;">
                <div class="post-meta__tag-list" style="display: inline-block;">
                    
                        <div class="article-tag">
                            
                                <a href="/tags/AutoCAD-API/">
                                    <span class="chip bg-color">AutoCAD API</span>
                                </a>
                            
                                <a href="/tags/C/">
                                    <span class="chip bg-color">C#</span>
                                </a>
                            
                        </div>
                    
                </div>
                <div class="post_share" style="zoom: 80%; width: fit-content; display: inline-block; float: right; margin: -0.15rem 0;">
                    <link rel="stylesheet" type="text/css" href="/libs/share/css/share.min.css">
<div id="article-share">

    
    <div class="social-share" data-sites="twitter,facebook,google,wechat,weibo,linkedin" data-wechat-qrcode-helper="<p>微信扫一扫即可分享！</p>"></div>
    <script src="/libs/share/js/social-share.min.js"></script>
    

    

</div>

                </div>
            </div>
            
        </div>
    </div>

    

    

    

    

    

    

    

<article id="prenext-posts" class="prev-next articles">
    <div class="row article-row">
        
        <div class="article col s12 m6" data-aos="fade-up" data-aos="fade-up">
            <div class="article-badge left-badge text-color">
                <i class="far fa-dot-circle"></i>&nbsp;Current
            </div>
            <div class="card">
                <a href="/2020/08/30/20200830AutoCAD%20developer's%20tools%20--%20Selection/">
                    <div class="card-image">
                        
                        
                        <img src="/medias/featureimages/19.jpg" class="responsive-img" alt="05. Selection">
                        
                        <span class="card-title">05. Selection</span>
                    </div>
                </a>
                <div class="card-content article-content">
                    <div class="summary block-with-text">
                        
                            Introduction
Today we will learn how to interact with AutoCAD.
Select Objects in the Drawing Area
You can select objects
                        
                    </div>
                    <div class="publish-info">
                            <span class="publish-date">
                                <i class="far fa-clock fa-fw icon-date"></i>2020-08-30
                            </span>
                        <span class="publish-author">
                            
                            <i class="fas fa-bookmark fa-fw icon-category"></i>
                            
                            <a href="/categories/August-2020/" class="post-category">
                                    August 2020
                                </a>
                            
                            
                        </span>
                    </div>
                </div>

                
                <div class="card-action article-tags">
                    
                    <a href="/tags/AutoCAD-API/">
                        <span class="chip bg-color">AutoCAD API</span>
                    </a>
                    
                    <a href="/tags/C/">
                        <span class="chip bg-color">C#</span>
                    </a>
                    
                </div>
                
            </div>
        </div>
        
        
        <div class="article col s12 m6" data-aos="fade-up">
            <div class="article-badge right-badge text-color">
                Next&nbsp;<i class="fas fa-chevron-right"></i>
            </div>
            <div class="card">
                <a href="/2020/08/25/20200825AutoCAD%20developer's%20tools%20--%20Modify%20the%20drawable%20object/">
                    <div class="card-image">
                        
                        
                        <img src="/medias/featureimages/14.jpg" class="responsive-img" alt="04. Modify the drawable object">
                        
                        <span class="card-title">04. Modify the drawable object</span>
                    </div>
                </a>
                <div class="card-content article-content">
                    <div class="summary block-with-text">
                        
                            Introduction
After learning how to draw a line with AutoCAD API, we can use similar way to create other drawable objects
                        
                    </div>
                    <div class="publish-info">
                            <span class="publish-date">
                                <i class="far fa-clock fa-fw icon-date"></i>2020-08-25
                            </span>
                        <span class="publish-author">
                            
                            <i class="fas fa-bookmark fa-fw icon-category"></i>
                            
                            <a href="/categories/August-2020/" class="post-category">
                                    August 2020
                                </a>
                            
                            
                        </span>
                    </div>
                </div>
                
                <div class="card-action article-tags">
                    
                    <a href="/tags/AutoCAD-API/">
                        <span class="chip bg-color">AutoCAD API</span>
                    </a>
                    
                    <a href="/tags/C/">
                        <span class="chip bg-color">C#</span>
                    </a>
                    
                </div>
                
            </div>
        </div>
        
    </div>
</article>

</div>



<!-- 代码块功能依赖 -->
<script type="text/javascript" src="/libs/codeBlock/codeBlockFuction.js"></script>

<!-- 代码语言 -->

<script type="text/javascript" src="/libs/codeBlock/codeLang.js"></script>


<!-- 代码块复制 -->

<script type="text/javascript" src="/libs/codeBlock/codeCopy.js"></script>


<!-- 代码块收缩 -->

<script type="text/javascript" src="/libs/codeBlock/codeShrink.js"></script>


<!-- 代码块折行 -->

<style type="text/css">
code[class*="language-"], pre[class*="language-"] { white-space: pre !important; }
</style>


    </div>
    <div id="toc-aside" class="expanded col l3 hide-on-med-and-down">
        <div class="toc-widget">
            <div class="toc-title"><i class="far fa-list-alt"></i>&nbsp;&nbsp;TOC</div>
            <div id="toc-content"></div>
        </div>
    </div>
</div>

<!-- TOC 悬浮按钮. -->

<div id="floating-toc-btn" class="hide-on-med-and-down">
    <a class="btn-floating btn-large bg-color">
        <i class="fas fa-list-ul"></i>
    </a>
</div>


<script src="/libs/tocbot/tocbot.min.js"></script>
<script>
    $(function () {
        tocbot.init({
            tocSelector: '#toc-content',
            contentSelector: '#articleContent',
            headingsOffset: -($(window).height() * 0.4 - 45),
            collapseDepth: Number('0'),
            headingSelector: 'h2, h3, h4'
        });

        // modify the toc link href to support Chinese.
        let i = 0;
        let tocHeading = 'toc-heading-';
        $('#toc-content a').each(function () {
            $(this).attr('href', '#' + tocHeading + (++i));
        });

        // modify the heading title id to support Chinese.
        i = 0;
        $('#articleContent').children('h2, h3, h4').each(function () {
            $(this).attr('id', tocHeading + (++i));
        });

        // Set scroll toc fixed.
        let tocHeight = parseInt($(window).height() * 0.4 - 64);
        let $tocWidget = $('.toc-widget');
        $(window).scroll(function () {
            let scroll = $(window).scrollTop();
            /* add post toc fixed. */
            if (scroll > tocHeight) {
                $tocWidget.addClass('toc-fixed');
            } else {
                $tocWidget.removeClass('toc-fixed');
            }
        });

        
        /* 修复文章卡片 div 的宽度. */
        let fixPostCardWidth = function (srcId, targetId) {
            let srcDiv = $('#' + srcId);
            if (srcDiv.length === 0) {
                return;
            }

            let w = srcDiv.width();
            if (w >= 450) {
                w = w + 21;
            } else if (w >= 350 && w < 450) {
                w = w + 18;
            } else if (w >= 300 && w < 350) {
                w = w + 16;
            } else {
                w = w + 14;
            }
            $('#' + targetId).width(w);
        };

        // 切换TOC目录展开收缩的相关操作.
        const expandedClass = 'expanded';
        let $tocAside = $('#toc-aside');
        let $mainContent = $('#main-content');
        $('#floating-toc-btn .btn-floating').click(function () {
            if ($tocAside.hasClass(expandedClass)) {
                $tocAside.removeClass(expandedClass).hide();
                $mainContent.removeClass('l9');
            } else {
                $tocAside.addClass(expandedClass).show();
                $mainContent.addClass('l9');
            }
            fixPostCardWidth('artDetail', 'prenext-posts');
        });
        
    });
</script>

    

</main>




    <footer class="page-footer bg-color">
    
        <link rel="stylesheet" href="/libs/aplayer/APlayer.min.css">
<style>
    .aplayer .aplayer-lrc p {
        
        display: none;
        
        font-size: 12px;
        font-weight: 700;
        line-height: 16px !important;
    }

    .aplayer .aplayer-lrc p.aplayer-lrc-current {
        
        display: none;
        
        font-size: 15px;
        color: #42b983;
    }

    
    .aplayer.aplayer-fixed.aplayer-narrow .aplayer-body {
        left: -66px !important;
    }

    .aplayer.aplayer-fixed.aplayer-narrow .aplayer-body:hover {
        left: 0px !important;
    }

    
</style>
<div class="">
    
    <div class="row">
        <meting-js class="col l8 offset-l2 m10 offset-m1 s12"
                   server="netease"
                   type="playlist"
                   id="503838841"
                   fixed='true'
                   autoplay='false'
                   theme='#42b983'
                   loop='all'
                   order='random'
                   preload='auto'
                   volume='0.7'
                   list-folded='true'
        >
        </meting-js>
    </div>
</div>

<script src="/libs/aplayer/APlayer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js"></script>

    
    <div class="container row center-align" style="margin-bottom: 0px !important;">
        <div class="col s12 m8 l8 copy-right">
            Copyright&nbsp;&copy;
            <span id="year">2020</span>
            <a href="/about" target="_blank">Ford Yang</a>
            |&nbsp;Powered by&nbsp;<a href="https://hexo.io/" target="_blank">Hexo</a>
            |&nbsp;Theme&nbsp;<a href="https://github.com/blinkfox/hexo-theme-matery" target="_blank">Matery</a>
            <br>
            
            
            
            
            
            
            <span id="busuanzi_container_site_pv">
                |&nbsp;<i class="far fa-eye"></i>&nbsp;总访问量:&nbsp;<span id="busuanzi_value_site_pv"
                    class="white-color"></span>&nbsp;次
            </span>
            
            
            <br>
            
            <br>
            
        </div>
        <div class="col s12 m4 l4 social-link social-statis">


    <a href="mailto:yangfan7014@gmail.com" class="tooltipped" target="_blank" data-tooltip="邮件联系我" data-position="top" data-delay="50">
        <i class="fas fa-envelope-open"></i>
    </a>







    <a href="tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=849042681" class="tooltipped" target="_blank" data-tooltip="QQ联系我: 849042681" data-position="top" data-delay="50">
        <i class="fab fa-qq"></i>
    </a>







</div>
    </div>
</footer>

<div class="progress-bar"></div>


    <!-- 搜索遮罩框 -->
<div id="searchModal" class="modal">
    <div class="modal-content">
        <div class="search-header">
            <span class="title"><i class="fas fa-search"></i>&nbsp;&nbsp;Search</span>
            <input type="search" id="searchInput" name="s" placeholder="Please enter a search keyword"
                   class="search-input">
        </div>
        <div id="searchResult"></div>
    </div>
</div>

<script src="/js/search.js"></script>
<script type="text/javascript">
$(function () {
    searchFunc("/search.xml", 'searchInput', 'searchResult');
});
</script>

    <!-- 回到顶部按钮 -->
<div id="backTop" class="top-scroll">
    <a class="btn-floating btn-large waves-effect waves-light" href="#!">
        <i class="fas fa-arrow-up"></i>
    </a>
</div>


    <script src="/libs/materialize/materialize.min.js"></script>
    <script src="/libs/masonry/masonry.pkgd.min.js"></script>
    <script src="/libs/aos/aos.js"></script>
    <script src="/libs/scrollprogress/scrollProgress.min.js"></script>
    <script src="/libs/lightGallery/js/lightgallery-all.min.js"></script>
    <script src="/js/matery.js"></script>

    <!-- Baidu Analytics -->

    <!-- Baidu Push -->

<script>
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        } else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>

    
    
    <script async src="/libs/others/busuanzi.pure.mini.js"></script>
    

    

    

    

    

    

    
    <script src="/libs/instantpage/instantpage.js" type="module"></script>
    

</body>

</html>
